source $HOME/.zplug/init.zsh

zplug "lib/function", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "$ZDOTDIR", from:local, use:mattie.zsh-theme, as:theme

# ask to install new plugins
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

HYPHEN_INSENSITIVE="true"

DISABLE_AUTO_TITLE="true"

setopt AUTO_CD

# source local settings
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi

# source aliases
if [ -f $ZDOTDIR/.aliases ]; then
  source $ZDOTDIR/.aliases
fi

# source scripts
for file in $ZDOTDIR/functions/*; do
  source "$file"
done
