source $HOME/.zplug/init.zsh

zplug "lib/function", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/common-aliases", from:oh-my-zsh
zplug "plugins/git-extras", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug denysdovhan/spaceship-prompt, use:spaceship.zsh, from:github, as:theme

# ask to install new plugins
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# set zsh options
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
setopt AUTO_CD

# set theme options
SPACESHIP_NODE_SHOW="false"

# source local settings
if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

# source scripts
for file in $ZDOTDIR/functions/*(.); do
  source "$file"
done

# source aliases
if [ -f $ZDOTDIR/.aliases ]; then
  source $ZDOTDIR/.aliases
fi

# source tmuxinator
if [ -f ~/.bin/tmuxinator.zsh ]; then
  source ~/.bin/tmuxinator.zsh
fi

