source $HOME/.zplug/init.zsh

zplug "lib/completion", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug denysdovhan/spaceship-prompt, use:spaceship.zsh, from:github, as:theme

# ask to install new plugins
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

# add nvm
source $NVM_DIR/nvm.sh

# Set up pyenv shims in PATH
export PATH="$PYENVDIR/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# set zsh options
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_TITLE="true"
setopt AUTO_CD

# set theme options
SPACESHIP_VI_MODE_SHOW="false"
SPACESHIP_TIME_SHOW="true"
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""

# source scripts
for file in $ZDOTDIR/functions/*(.); do
  source "$file"
done

# source aliases
if [ -f $ZDOTDIR/.aliases ]; then
  source $ZDOTDIR/.aliases
fi

# source local settings
if [ -f $HOME/.zshrc.local ]; then
  source $HOME/.zshrc.local
fi
